---
- name: install monitoring stack
  hosts: _Name__Name_Name_Instance_in_Public_Subnet_with_OpenVPN
  become: yes
  roles:
  - zabbix_serv 


- name: It will be install docker for my servers and node-exporter
  hosts: _Name__Name_Name_WebServer_in_ASG
  become: yes

  roles:
    - deploy_docker_and_zabbix_proxy 