---
plugin: aws_ec2
aws_profile: default

regions:  us-east-1 #- add, after play script


filters:
  instance-state-name:
    - running

keyed_groups:
  - key: tags

# keyed_groups:
#   - key: tags
#     prefix: tag
#   - prefix: instance_type
#     key: instance_type
#   - key: placement.region
#     prefix: aws_region

compose:
  ansible_host: public_ip_address if public_ip_address is defined else private_ip_address